In [537]:
import sqlite3
import pandas as pd
from pybaseball import standings
from pybaseball import team_batting

Eventually I import the different files and so the user gets to choose
df.head()
df.columns
df.info()
basic panda functions to use asap for new things

This is my new project to learn more about Jupyter Notebooks, python, and SQL

teams          → pybaseball standings data
team_records   → cleaned standings DataFrame
teams_api      → raw MLB API team data

In [538]:
teams = standings(2025)

In [539]:
teams[0]

                  Tm   W   L  W-L%    GB
1  Toronto Blue Jays  94  68  .580    --
2   New York Yankees  94  68  .580    --
3     Boston Red Sox  89  73  .549   5.0
4     Tampa Bay Rays  77  85  .475  17.0
5  Baltimore Orioles  75  87  .463  19.0

In [540]:
df = pd.concat(teams, ignore_index=True)
df
df.shape

(30, 5)

In [541]:
#looking at the exact cols in the database
df.head

<bound method NDFrame.head of                        Tm   W    L  W-L%    GB
0       Toronto Blue Jays  94   68  .580    --
1        New York Yankees  94   68  .580    --
2          Boston Red Sox  89   73  .549   5.0
3          Tampa Bay Rays  77   85  .475  17.0
4       Baltimore Orioles  75   87  .463  19.0
5     Cleveland Guardians  88   74  .543    --
6          Detroit Tigers  87   75  .537   1.0
7      Kansas City Royals  82   80  .506   6.0
8         Minnesota Twins  70   92  .432  18.0
9       Chicago White Sox  60  102  .370  28.0
10       Seattle Mariners  90   72  .556    --
11         Houston Astros  87   75  .537   3.0
12          Texas Rangers  81   81  .500   9.0
13              Athletics  76   86  .469  14.0
14     Los Angeles Angels  72   90  .444  18.0
15  Philadelphia Phillies  96   66  .593    --
16          New York Mets  83   79  .512  13.0
17          Miami Marlins  79   83  .488  17.0
18         Atlanta Braves  76   86  .469  20.0
19   Washington Nationals  66   96  .407  30.0
20      Milwaukee Brewers  97   65  .599    --
21           Chicago Cubs  92   70  .568   5.0
22        Cincinnati Reds  83   79  .512  14.0
23    St. Louis Cardinals  78   84  .481  19.0
24     Pittsburgh Pirates  71   91  .438  26.0
25    Los Angeles Dodgers  93   69  .574    --
26       San Diego Padres  90   72  .556   3.0
27   San Francisco Giants  81   81  .500  12.0
28   Arizona Diamondbacks  80   82  .494  13.0
29       Colorado Rockies  43  119  .265  50.0>

In [542]:
df.columns

Index(['Tm', 'W', 'L', 'W-L%', 'GB'], dtype='str')

In [543]:
team_records = df[["Tm", "W", "L", "W-L%","GB"]]
team_records.head()
team_win_rate = df[["W-L%"]]
team_win_rate

    W-L%
0   .580
1   .580
2   .549
3   .475
4   .463
5   .543
6   .537
7   .506
8   .432
9   .370
10  .556
11  .537
12  .500
13  .469
14  .444
15  .593
16  .512
17  .488
18  .469
19  .407
20  .599
21  .568
22  .512
23  .481
24  .438
25  .574
26  .556
27  .500
28  .494
29  .265

In [544]:
team_records.sort_values(by="W")

                       Tm   W    L  W-L%    GB
29       Colorado Rockies  43  119  .265  50.0
9       Chicago White Sox  60  102  .370  28.0
19   Washington Nationals  66   96  .407  30.0
8         Minnesota Twins  70   92  .432  18.0
24     Pittsburgh Pirates  71   91  .438  26.0
14     Los Angeles Angels  72   90  .444  18.0
4       Baltimore Orioles  75   87  .463  19.0
13              Athletics  76   86  .469  14.0
18         Atlanta Braves  76   86  .469  20.0
3          Tampa Bay Rays  77   85  .475  17.0
23    St. Louis Cardinals  78   84  .481  19.0
17          Miami Marlins  79   83  .488  17.0
28   Arizona Diamondbacks  80   82  .494  13.0
12          Texas Rangers  81   81  .500   9.0
27   San Francisco Giants  81   81  .500  12.0
7      Kansas City Royals  82   80  .506   6.0
16          New York Mets  83   79  .512  13.0
22        Cincinnati Reds  83   79  .512  14.0
6          Detroit Tigers  87   75  .537   1.0
11         Houston Astros  87   75  .537   3.0
5     Cleveland Guardians  88   74  .543    --
2          Boston Red Sox  89   73  .549   5.0
10       Seattle Mariners  90   72  .556    --
26       San Diego Padres  90   72  .556   3.0
21           Chicago Cubs  92   70  .568   5.0
25    Los Angeles Dodgers  93   69  .574    --
0       Toronto Blue Jays  94   68  .580    --
1        New York Yankees  94   68  .580    --
15  Philadelphia Phillies  96   66  .593    --
20      Milwaukee Brewers  97   65  .599    --

In [545]:
team_records.dtypes

Tm      str
W       str
L       str
W-L%    str
GB      str
dtype: object

In [546]:
team_records["W"] = pd.to_numeric(team_records["W"])
team_records["L"] = pd.to_numeric(team_records["L"])
team_records["W-L%"] = pd.to_numeric(team_records["W-L%"])

In [547]:
team_records.dtypes

Tm          str
W         int64
L         int64
W-L%    float64
GB          str
dtype: object

In [548]:
team_records[team_records["W"] >= 90]

                       Tm   W   L   W-L%   GB
0       Toronto Blue Jays  94  68  0.580   --
1        New York Yankees  94  68  0.580   --
10       Seattle Mariners  90  72  0.556   --
15  Philadelphia Phillies  96  66  0.593   --
20      Milwaukee Brewers  97  65  0.599   --
21           Chicago Cubs  92  70  0.568  5.0
25    Los Angeles Dodgers  93  69  0.574   --
26       San Diego Padres  90  72  0.556  3.0

In [549]:
type(team_records["W"].iloc[0])

numpy.int64

In [550]:
team_records[team_records["W-L%"] >= 90]

Empty DataFrame
Columns: [Tm, W, L, W-L%, GB]
Index: []

In [551]:
team_Tm_W = df[["Tm", "W"]]
team_Tm_W

                       Tm   W
0       Toronto Blue Jays  94
1        New York Yankees  94
2          Boston Red Sox  89
3          Tampa Bay Rays  77
4       Baltimore Orioles  75
5     Cleveland Guardians  88
6          Detroit Tigers  87
7      Kansas City Royals  82
8         Minnesota Twins  70
9       Chicago White Sox  60
10       Seattle Mariners  90
11         Houston Astros  87
12          Texas Rangers  81
13              Athletics  76
14     Los Angeles Angels  72
15  Philadelphia Phillies  96
16          New York Mets  83
17          Miami Marlins  79
18         Atlanta Braves  76
19   Washington Nationals  66
20      Milwaukee Brewers  97
21           Chicago Cubs  92
22        Cincinnati Reds  83
23    St. Louis Cardinals  78
24     Pittsburgh Pirates  71
25    Los Angeles Dodgers  93
26       San Diego Padres  90
27   San Francisco Giants  81
28   Arizona Diamondbacks  80
29       Colorado Rockies  43

In [552]:
df.compare

<bound method DataFrame.compare of                        Tm   W    L  W-L%    GB
0       Toronto Blue Jays  94   68  .580    --
1        New York Yankees  94   68  .580    --
2          Boston Red Sox  89   73  .549   5.0
3          Tampa Bay Rays  77   85  .475  17.0
4       Baltimore Orioles  75   87  .463  19.0
5     Cleveland Guardians  88   74  .543    --
6          Detroit Tigers  87   75  .537   1.0
7      Kansas City Royals  82   80  .506   6.0
8         Minnesota Twins  70   92  .432  18.0
9       Chicago White Sox  60  102  .370  28.0
10       Seattle Mariners  90   72  .556    --
11         Houston Astros  87   75  .537   3.0
12          Texas Rangers  81   81  .500   9.0
13              Athletics  76   86  .469  14.0
14     Los Angeles Angels  72   90  .444  18.0
15  Philadelphia Phillies  96   66  .593    --
16          New York Mets  83   79  .512  13.0
17          Miami Marlins  79   83  .488  17.0
18         Atlanta Braves  76   86  .469  20.0
19   Washington Nationals  66   96  .407  30.0
20      Milwaukee Brewers  97   65  .599    --
21           Chicago Cubs  92   70  .568   5.0
22        Cincinnati Reds  83   79  .512  14.0
23    St. Louis Cardinals  78   84  .481  19.0
24     Pittsburgh Pirates  71   91  .438  26.0
25    Los Angeles Dodgers  93   69  .574    --
26       San Diego Padres  90   72  .556   3.0
27   San Francisco Giants  81   81  .500  12.0
28   Arizona Diamondbacks  80   82  .494  13.0
29       Colorado Rockies  43  119  .265  50.0>

In [553]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tm      30 non-null     str
 1   W       30 non-null     str
 2   L       30 non-null     str
 3   W-L%    30 non-null     str
 4   GB      30 non-null     str
dtypes: str(5)
memory usage: 2.1 KB

In [554]:
team_records["Win_Percentage"] = team_records["W"] / (team_records["W"] + team_records["L"])

team_records

                       Tm   W    L   W-L%    GB  Win_Percentage
0       Toronto Blue Jays  94   68  0.580    --        0.580247
1        New York Yankees  94   68  0.580    --        0.580247
2          Boston Red Sox  89   73  0.549   5.0        0.549383
3          Tampa Bay Rays  77   85  0.475  17.0        0.475309
4       Baltimore Orioles  75   87  0.463  19.0        0.462963
5     Cleveland Guardians  88   74  0.543    --        0.543210
6          Detroit Tigers  87   75  0.537   1.0        0.537037
7      Kansas City Royals  82   80  0.506   6.0        0.506173
8         Minnesota Twins  70   92  0.432  18.0        0.432099
9       Chicago White Sox  60  102  0.370  28.0        0.370370
10       Seattle Mariners  90   72  0.556    --        0.555556
11         Houston Astros  87   75  0.537   3.0        0.537037
12          Texas Rangers  81   81  0.500   9.0        0.500000
13              Athletics  76   86  0.469  14.0        0.469136
14     Los Angeles Angels  72   90  0.444  18.0        0.444444
15  Philadelphia Phillies  96   66  0.593    --        0.592593
16          New York Mets  83   79  0.512  13.0        0.512346
17          Miami Marlins  79   83  0.488  17.0        0.487654
18         Atlanta Braves  76   86  0.469  20.0        0.469136
19   Washington Nationals  66   96  0.407  30.0        0.407407
20      Milwaukee Brewers  97   65  0.599    --        0.598765
21           Chicago Cubs  92   70  0.568   5.0        0.567901
22        Cincinnati Reds  83   79  0.512  14.0        0.512346
23    St. Louis Cardinals  78   84  0.481  19.0        0.481481
24     Pittsburgh Pirates  71   91  0.438  26.0        0.438272
25    Los Angeles Dodgers  93   69  0.574    --        0.574074
26       San Diego Padres  90   72  0.556   3.0        0.555556
27   San Francisco Giants  81   81  0.500  12.0        0.500000
28   Arizona Diamondbacks  80   82  0.494  13.0        0.493827
29       Colorado Rockies  43  119  0.265  50.0        0.265432

Here is stuff from batting now

In [555]:
#batting = team_batting(2025, league="all")

In [556]:
#batting.head()
#batting.shape
#batting.columns
#batting.info()

Here is stuff for the 2024 season will eventually compare stuff

In [557]:
teams2024 = standings(2024)
df2024 = pd.concat(teams2024, ignore_index=True)
df2024
df2024.shape

(30, 5)

In [558]:
df2024.columns

Index(['Tm', 'W', 'L', 'W-L%', 'GB'], dtype='str')

In [559]:
df2024.head

<bound method NDFrame.head of                        Tm   W    L  W-L%    GB
0        New York Yankees  94   68  .580    --
1       Baltimore Orioles  91   71  .562   3.0
2          Boston Red Sox  81   81  .500  13.0
3          Tampa Bay Rays  80   82  .494  14.0
4       Toronto Blue Jays  74   88  .457  20.0
5     Cleveland Guardians  92   69  .571    --
6      Kansas City Royals  86   76  .531   6.5
7          Detroit Tigers  86   76  .531   6.5
8         Minnesota Twins  82   80  .506  10.5
9       Chicago White Sox  41  121  .253  51.5
10         Houston Astros  88   73  .547    --
11       Seattle Mariners  85   77  .525   3.5
12          Texas Rangers  78   84  .481  10.5
13      Oakland Athletics  69   93  .426  19.5
14     Los Angeles Angels  63   99  .389  25.5
15  Philadelphia Phillies  95   67  .586    --
16         Atlanta Braves  89   73  .549   6.0
17          New York Mets  89   73  .549   6.0
18   Washington Nationals  71   91  .438  24.0
19          Miami Marlins  62  100  .383  33.0
20      Milwaukee Brewers  93   69  .574    --
21           Chicago Cubs  83   79  .512  10.0
22    St. Louis Cardinals  83   79  .512  10.0
23        Cincinnati Reds  77   85  .475  16.0
24     Pittsburgh Pirates  76   86  .469  17.0
25    Los Angeles Dodgers  98   64  .605    --
26       San Diego Padres  93   69  .574   5.0
27   Arizona Diamondbacks  89   73  .549   9.0
28   San Francisco Giants  80   82  .494  18.0
29       Colorado Rockies  61  101  .377  37.0>

In [560]:
df2024.compare

<bound method DataFrame.compare of                        Tm   W    L  W-L%    GB
0        New York Yankees  94   68  .580    --
1       Baltimore Orioles  91   71  .562   3.0
2          Boston Red Sox  81   81  .500  13.0
3          Tampa Bay Rays  80   82  .494  14.0
4       Toronto Blue Jays  74   88  .457  20.0
5     Cleveland Guardians  92   69  .571    --
6      Kansas City Royals  86   76  .531   6.5
7          Detroit Tigers  86   76  .531   6.5
8         Minnesota Twins  82   80  .506  10.5
9       Chicago White Sox  41  121  .253  51.5
10         Houston Astros  88   73  .547    --
11       Seattle Mariners  85   77  .525   3.5
12          Texas Rangers  78   84  .481  10.5
13      Oakland Athletics  69   93  .426  19.5
14     Los Angeles Angels  63   99  .389  25.5
15  Philadelphia Phillies  95   67  .586    --
16         Atlanta Braves  89   73  .549   6.0
17          New York Mets  89   73  .549   6.0
18   Washington Nationals  71   91  .438  24.0
19          Miami Marlins  62  100  .383  33.0
20      Milwaukee Brewers  93   69  .574    --
21           Chicago Cubs  83   79  .512  10.0
22    St. Louis Cardinals  83   79  .512  10.0
23        Cincinnati Reds  77   85  .475  16.0
24     Pittsburgh Pirates  76   86  .469  17.0
25    Los Angeles Dodgers  98   64  .605    --
26       San Diego Padres  93   69  .574   5.0
27   Arizona Diamondbacks  89   73  .549   9.0
28   San Francisco Giants  80   82  .494  18.0
29       Colorado Rockies  61  101  .377  37.0>

In [561]:
df2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tm      30 non-null     str
 1   W       30 non-null     str
 2   L       30 non-null     str
 3   W-L%    30 non-null     str
 4   GB      30 non-null     str
dtypes: str(5)
memory usage: 2.1 KB

## Different api
This is gonna be another api to pull data from to learn more about the team

In [562]:
%pip install MLB-StatsAPI

Requirement already satisfied: MLB-StatsAPI in c:\users\huelkes\appdata\local\programs\python\python312\lib\site-packages (1.9.0)
Requirement already satisfied: requests in c:\users\huelkes\appdata\local\programs\python\python312\lib\site-packages (from MLB-StatsAPI) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\huelkes\appdata\local\programs\python\python312\lib\site-packages (from requests->MLB-StatsAPI) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\huelkes\appdata\local\programs\python\python312\lib\site-packages (from requests->MLB-StatsAPI) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\huelkes\appdata\local\programs\python\python312\lib\site-packages (from requests->MLB-StatsAPI) (2.6.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\huelkes\appdata\local\programs\python\python312\lib\site-packages (from requests->MLB-StatsAPI) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [563]:
import statsapi

In [564]:
teams_api = statsapi.get("teams", {"sportId": 1})

In [565]:
teams_api["teams"][0]
teams_api

{'copyright': 'Copyright 2026 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt',
 'teams': [{'springLeague': {'id': 114,
    'name': 'Cactus League',
    'link': '/api/v1/league/114',
    'abbreviation': 'CL'},
   'allStarStatus': 'N',
   'id': 133,
   'name': 'Athletics',
   'link': '/api/v1/teams/133',
   'season': 2026,
   'venue': {'id': 2529,
    'name': 'Sutter Health Park',
    'link': '/api/v1/venues/2529'},
   'springVenue': {'id': 2507, 'link': '/api/v1/venues/2507'},
   'teamCode': 'ath',
   'fileCode': 'ath',
   'abbreviation': 'ATH',
   'teamName': 'Athletics',
   'locationName': 'Sacramento',
   'firstYearOfPlay': '1901',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 200,
    'name': 'American League West',
    'link': '/api/v1/divisions/200'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Athletics',
   'franchiseName': 'Athletics',
   'clubName': 'Athletics',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 134,
   'name': 'Pittsburgh Pirates',
   'link': '/api/v1/teams/134',
   'season': 2026,
   'venue': {'id': 31, 'name': 'PNC Park', 'link': '/api/v1/venues/31'},
   'springVenue': {'id': 2526, 'link': '/api/v1/venues/2526'},
   'teamCode': 'pit',
   'fileCode': 'pit',
   'abbreviation': 'PIT',
   'teamName': 'Pirates',
   'locationName': 'Pittsburgh',
   'firstYearOfPlay': '1882',
   'league': {'id': 104,
    'name': 'National League',
    'link': '/api/v1/league/104'},
   'division': {'id': 205,
    'name': 'National League Central',
    'link': '/api/v1/divisions/205'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Pittsburgh',
   'franchiseName': 'Pittsburgh',
   'clubName': 'Pirates',
   'active': True},
  {'springLeague': {'id': 114,
    'name': 'Cactus League',
    'link': '/api/v1/league/114',
    'abbreviation': 'CL'},
   'allStarStatus': 'N',
   'id': 135,
   'name': 'San Diego Padres',
   'link': '/api/v1/teams/135',
   'season': 2026,
   'venue': {'id': 2680, 'name': 'Petco Park', 'link': '/api/v1/venues/2680'},
   'springVenue': {'id': 2530, 'link': '/api/v1/venues/2530'},
   'teamCode': 'sdn',
   'fileCode': 'sd',
   'abbreviation': 'SD',
   'teamName': 'Padres',
   'locationName': 'San Diego',
   'firstYearOfPlay': '1968',
   'league': {'id': 104,
    'name': 'National League',
    'link': '/api/v1/league/104'},
   'division': {'id': 203,
    'name': 'National League West',
    'link': '/api/v1/divisions/203'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'San Diego',
   'franchiseName': 'San Diego',
   'clubName': 'Padres',
   'active': True},
  {'springLeague': {'id': 114,
    'name': 'Cactus League',
    'link': '/api/v1/league/114',
    'abbreviation': 'CL'},
   'allStarStatus': 'N',
   'id': 136,
   'name': 'Seattle Mariners',
   'link': '/api/v1/teams/136',
   'season': 2026,
   'venue': {'id': 680, 'name': 'T-Mobile Park', 'link': '/api/v1/venues/680'},
   'springVenue': {'id': 2530, 'link': '/api/v1/venues/2530'},
   'teamCode': 'sea',
   'fileCode': 'sea',
   'abbreviation': 'SEA',
   'teamName': 'Mariners',
   'locationName': 'Seattle',
   'firstYearOfPlay': '1977',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 200,
    'name': 'American League West',
    'link': '/api/v1/divisions/200'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Seattle',
   'franchiseName': 'Seattle',
   'clubName': 'Mariners',
   'active': True},
  {'springLeague': {'id': 114,
    'name': 'Cactus League',
    'link': '/api/v1/league/114',
    'abbreviation': 'CL'},
   'allStarStatus': 'N',
   'id': 137,
   'name': 'San Francisco Giants',
   'link': '/api/v1/teams/137',
   'season': 2026,
   'venue': {'id': 2395, 'name': 'Oracle Park', 'link': '/api/v1/venues/2395'},
   'springVenue': {'id': 2532, 'link': '/api/v1/venues/2532'},
   'teamCode': 'sfn',
   'fileCode': 'sf',
   'abbreviation': 'SF',
   'teamName': 'Giants',
   'locationName': 'San Francisco',
   'firstYearOfPlay': '1883',
   'league': {'id': 104,
    'name': 'National League',
    'link': '/api/v1/league/104'},
   'division': {'id': 203,
    'name': 'National League West',
    'link': '/api/v1/divisions/203'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'San Francisco',
   'franchiseName': 'San Francisco',
   'clubName': 'Giants',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 138,
   'name': 'St. Louis Cardinals',
   'link': '/api/v1/teams/138',
   'season': 2026,
   'venue': {'id': 2889,
    'name': 'Busch Stadium',
    'link': '/api/v1/venues/2889'},
   'springVenue': {'id': 2520, 'link': '/api/v1/venues/2520'},
   'teamCode': 'sln',
   'fileCode': 'stl',
   'abbreviation': 'STL',
   'teamName': 'Cardinals',
   'locationName': 'St. Louis',
   'firstYearOfPlay': '1892',
   'league': {'id': 104,
    'name': 'National League',
    'link': '/api/v1/league/104'},
   'division': {'id': 205,
    'name': 'National League Central',
    'link': '/api/v1/divisions/205'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'St. Louis',
   'franchiseName': 'St. Louis',
   'clubName': 'Cardinals',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 139,
   'name': 'Tampa Bay Rays',
   'link': '/api/v1/teams/139',
   'season': 2026,
   'venue': {'id': 12, 'name': 'Tropicana Field', 'link': '/api/v1/venues/12'},
   'springVenue': {'id': 2534, 'link': '/api/v1/venues/2534'},
   'teamCode': 'tba',
   'fileCode': 'tb',
   'abbreviation': 'TB',
   'teamName': 'Rays',
   'locationName': 'St. Petersburg',
   'firstYearOfPlay': '1996',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 201,
    'name': 'American League East',
    'link': '/api/v1/divisions/201'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Tampa Bay',
   'franchiseName': 'Tampa Bay',
   'clubName': 'Rays',
   'active': True},
  {'springLeague': {'id': 114,
    'name': 'Cactus League',
    'link': '/api/v1/league/114',
    'abbreviation': 'CL'},
   'allStarStatus': 'N',
   'id': 140,
   'name': 'Texas Rangers',
   'link': '/api/v1/teams/140',
   'season': 2026,
   'venue': {'id': 5325,
    'name': 'Globe Life Field',
    'link': '/api/v1/venues/5325'},
   'springVenue': {'id': 2603, 'link': '/api/v1/venues/2603'},
   'teamCode': 'tex',
   'fileCode': 'tex',
   'abbreviation': 'TEX',
   'teamName': 'Rangers',
   'locationName': 'Arlington',
   'firstYearOfPlay': '1961',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 200,
    'name': 'American League West',
    'link': '/api/v1/divisions/200'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Texas',
   'franchiseName': 'Texas',
   'clubName': 'Rangers',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 141,
   'name': 'Toronto Blue Jays',
   'link': '/api/v1/teams/141',
   'season': 2026,
   'venue': {'id': 14, 'name': 'Rogers Centre', 'link': '/api/v1/venues/14'},
   'springVenue': {'id': 2536, 'link': '/api/v1/venues/2536'},
   'teamCode': 'tor',
   'fileCode': 'tor',
   'abbreviation': 'TOR',
   'teamName': 'Blue Jays',
   'locationName': 'Toronto',
   'firstYearOfPlay': '1977',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 201,
    'name': 'American League East',
    'link': '/api/v1/divisions/201'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Toronto',
   'franchiseName': 'Toronto',
   'clubName': 'Blue Jays',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 142,
   'name': 'Minnesota Twins',
   'link': '/api/v1/teams/142',
   'season': 2026,
   'venue': {'id': 3312,
    'name': 'Target Field',
    'link': '/api/v1/venues/3312'},
   'springVenue': {'id': 2862, 'link': '/api/v1/venues/2862'},
   'teamCode': 'min',
   'fileCode': 'min',
   'abbreviation': 'MIN',
   'teamName': 'Twins',
   'locationName': 'Minneapolis',
   'firstYearOfPlay': '1901',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 202,
    'name': 'American League Central',
    'link': '/api/v1/divisions/202'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Minnesota',
   'franchiseName': 'Minnesota',
   'clubName': 'Twins',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 143,
   'name': 'Philadelphia Phillies',
   'link': '/api/v1/teams/143',
   'season': 2026,
   'venue': {'id': 2681,
    'name': 'Citizens Bank Park',
    'link': '/api/v1/venues/2681'},
   'springVenue': {'id': 2700, 'link': '/api/v1/venues/2700'},
   'teamCode': 'phi',
   'fileCode': 'phi',
   'abbreviation': 'PHI',
   'teamName': 'Phillies',
   'locationName': 'Philadelphia',
   'firstYearOfPlay': '1883',
   'league': {'id': 104,
    'name': 'National League',
    'link': '/api/v1/league/104'},
   'division': {'id': 204,
    'name': 'National League East',
    'link': '/api/v1/divisions/204'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Philadelphia',
   'franchiseName': 'Philadelphia',
   'clubName': 'Phillies',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 144,
   'name': 'Atlanta Braves',
   'link': '/api/v1/teams/144',
   'season': 2026,
   'venue': {'id': 4705, 'name': 'Truist Park', 'link': '/api/v1/venues/4705'},
   'springVenue': {'id': 5380, 'link': '/api/v1/venues/5380'},
   'teamCode': 'atl',
   'fileCode': 'atl',
   'abbreviation': 'ATL',
   'teamName': 'Braves',
   'locationName': 'Atlanta',
   'firstYearOfPlay': '1871',
   'league': {'id': 104,
    'name': 'National League',
    'link': '/api/v1/league/104'},
   'division': {'id': 204,
    'name': 'National League East',
    'link': '/api/v1/divisions/204'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Atlanta',
   'franchiseName': 'Atlanta',
   'clubName': 'Braves',
   'active': True},
  {'springLeague': {'id': 114,
    'name': 'Cactus League',
    'link': '/api/v1/league/114',
    'abbreviation': 'CL'},
   'allStarStatus': 'N',
   'id': 145,
   'name': 'Chicago White Sox',
   'link': '/api/v1/teams/145',
   'season': 2026,
   'venue': {'id': 4, 'name': 'Rate Field', 'link': '/api/v1/venues/4'},
   'springVenue': {'id': 3809, 'link': '/api/v1/venues/3809'},
   'teamCode': 'cha',
   'fileCode': 'cws',
   'abbreviation': 'CWS',
   'teamName': 'White Sox',
   'locationName': 'Chicago',
   'firstYearOfPlay': '1901',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 202,
    'name': 'American League Central',
    'link': '/api/v1/divisions/202'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Chi White Sox',
   'franchiseName': 'Chicago',
   'clubName': 'White Sox',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 146,
   'name': 'Miami Marlins',
   'link': '/api/v1/teams/146',
   'season': 2026,
   'venue': {'id': 4169,
    'name': 'loanDepot park',
    'link': '/api/v1/venues/4169'},
   'springVenue': {'id': 2520, 'link': '/api/v1/venues/2520'},
   'teamCode': 'mia',
   'fileCode': 'mia',
   'abbreviation': 'MIA',
   'teamName': 'Marlins',
   'locationName': 'Miami',
   'firstYearOfPlay': '1991',
   'league': {'id': 104,
    'name': 'National League',
    'link': '/api/v1/league/104'},
   'division': {'id': 204,
    'name': 'National League East',
    'link': '/api/v1/divisions/204'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Miami',
   'franchiseName': 'Miami',
   'clubName': 'Marlins',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 147,
   'name': 'New York Yankees',
   'link': '/api/v1/teams/147',
   'season': 2026,
   'venue': {'id': 3313,
    'name': 'Yankee Stadium',
    'link': '/api/v1/venues/3313'},
   'springVenue': {'id': 2523, 'link': '/api/v1/venues/2523'},
   'teamCode': 'nya',
   'fileCode': 'nyy',
   'abbreviation': 'NYY',
   'teamName': 'Yankees',
   'locationName': 'Bronx',
   'firstYearOfPlay': '1903',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 201,
    'name': 'American League East',
    'link': '/api/v1/divisions/201'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'NY Yankees',
   'franchiseName': 'New York',
   'clubName': 'Yankees',
   'active': True},
  {'springLeague': {'id': 114,
    'name': 'Cactus League',
    'link': '/api/v1/league/114',
    'abbreviation': 'CL'},
   'allStarStatus': 'N',
   'id': 158,
   'name': 'Milwaukee Brewers',
   'link': '/api/v1/teams/158',
   'season': 2026,
   'venue': {'id': 32,
    'name': 'American Family Field',
    'link': '/api/v1/venues/32'},
   'springVenue': {'id': 2518, 'link': '/api/v1/venues/2518'},
   'teamCode': 'mil',
   'fileCode': 'mil',
   'abbreviation': 'MIL',
   'teamName': 'Brewers',
   'locationName': 'Milwaukee',
   'firstYearOfPlay': '1968',
   'league': {'id': 104,
    'name': 'National League',
    'link': '/api/v1/league/104'},
   'division': {'id': 205,
    'name': 'National League Central',
    'link': '/api/v1/divisions/205'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Milwaukee',
   'franchiseName': 'Milwaukee',
   'clubName': 'Brewers',
   'active': True},
  {'springLeague': {'id': 114,
    'name': 'Cactus League',
    'link': '/api/v1/league/114',
    'abbreviation': 'CL'},
   'allStarStatus': 'N',
   'id': 108,
   'name': 'Los Angeles Angels',
   'link': '/api/v1/teams/108',
   'season': 2026,
   'venue': {'id': 1, 'name': 'Angel Stadium', 'link': '/api/v1/venues/1'},
   'springVenue': {'id': 2500, 'link': '/api/v1/venues/2500'},
   'teamCode': 'ana',
   'fileCode': 'ana',
   'abbreviation': 'LAA',
   'teamName': 'Angels',
   'locationName': 'Anaheim',
   'firstYearOfPlay': '1961',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 200,
    'name': 'American League West',
    'link': '/api/v1/divisions/200'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'LA Angels',
   'franchiseName': 'Los Angeles',
   'clubName': 'Angels',
   'active': True},
  {'springLeague': {'id': 114,
    'name': 'Cactus League',
    'link': '/api/v1/league/114',
    'abbreviation': 'CL'},
   'allStarStatus': 'N',
   'id': 109,
   'name': 'Arizona Diamondbacks',
   'link': '/api/v1/teams/109',
   'season': 2026,
   'venue': {'id': 15, 'name': 'Chase Field', 'link': '/api/v1/venues/15'},
   'springVenue': {'id': 4249, 'link': '/api/v1/venues/4249'},
   'teamCode': 'ari',
   'fileCode': 'ari',
   'abbreviation': 'AZ',
   'teamName': 'D-backs',
   'locationName': 'Phoenix',
   'firstYearOfPlay': '1996',
   'league': {'id': 104,
    'name': 'National League',
    'link': '/api/v1/league/104'},
   'division': {'id': 203,
    'name': 'National League West',
    'link': '/api/v1/divisions/203'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Arizona',
   'franchiseName': 'Arizona',
   'clubName': 'Diamondbacks',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 110,
   'name': 'Baltimore Orioles',
   'link': '/api/v1/teams/110',
   'season': 2026,
   'venue': {'id': 2,
    'name': 'Oriole Park at Camden Yards',
    'link': '/api/v1/venues/2'},
   'springVenue': {'id': 2508, 'link': '/api/v1/venues/2508'},
   'teamCode': 'bal',
   'fileCode': 'bal',
   'abbreviation': 'BAL',
   'teamName': 'Orioles',
   'locationName': 'Baltimore',
   'firstYearOfPlay': '1901',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 201,
    'name': 'American League East',
    'link': '/api/v1/divisions/201'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Baltimore',
   'franchiseName': 'Baltimore',
   'clubName': 'Orioles',
   'active': True},
  {'springLeague': {'id': 115,
    'name': 'Grapefruit League',
    'link': '/api/v1/league/115',
    'abbreviation': 'GL'},
   'allStarStatus': 'N',
   'id': 111,
   'name': 'Boston Red Sox',
   'link': '/api/v1/teams/111',
   'season': 2026,
   'venue': {'id': 3, 'name': 'Fenway Park', 'link': '/api/v1/venues/3'},
   'springVenue': {'id': 4309, 'link': '/api/v1/venues/4309'},
   'teamCode': 'bos',
   'fileCode': 'bos',
   'abbreviation': 'BOS',
   'teamName': 'Red Sox',
   'locationName': 'Boston',
   'firstYearOfPlay': '1901',
   'league': {'id': 103,
    'name': 'American League',
    'link': '/api/v1/league/103'},
   'division': {'id': 201,
    'name': 'American League East',
    'link': '/api/v1/divisions/201'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Boston',
   'franchiseName': 'Boston',
   'clubName': 'Red Sox',
   'active': True},
  {'springLeague': {'id': 114,
    'name': 'Cactus League',
    'link': '/api/v1/league/114',
    'abbreviation': 'CL'},
   'allStarStatus': 'N',
   'id': 112,
   'name': 'Chicago Cubs',
   'link': '/api/v1/teams/112',
   'season': 2026,
   'venue': {'id': 17, 'name': 'Wrigley Field', 'link': '/api/v1/venues/17'},
   'springVenue': {'id': 4629, 'link': '/api/v1/venues/4629'},
   'teamCode': 'chn',
   'fileCode': 'chc',
   'abbreviation': 'CHC',
   'teamName': 'Cubs',
   'locationName': 'Chicago',
   'firstYearOfPlay': '1874',
   'league': {'id': 104,
    'name': 'National League',
    'link': '/api/v1/league/104'},
   'division': {'id': 205,
    'name': 'National League Central',
    'link': '/api/v1/divisions/205'},
   'sport': {'id': 1,
    'link': '/api/v1/sports/1',
    'name': 'Major League Baseball'},
   'shortName': 'Chi Cubs',
   'franchiseName': 'Chicago',
   'clubName': 'Cubs',
   'active': True},
  {'springLeague': {'id': 114,
    'name': 'Cactus League',

In [566]:
type(teams_api)

dict

In [567]:
type(teams_api["teams"])
len(teams_api["teams"])

30

Making Teams_api into a dataframe to make it look good

In [568]:
api_teams_df = pd.DataFrame(teams_api["teams"])

In [569]:
api_teams_df.head()

,springLeague,allStarStatus,id,name,link,season,venue,springVenue,teamCode,fileCode,...,teamName,locationName,firstYearOfPlay,league,division,sport,shortName,franchiseName,clubName,active
0,"{'id': 114, 'name': 'Cactus League', 'link': '...",N,133,Athletics,/api/v1/teams/133,2026,"{'id': 2529, 'name': 'Sutter Health Park', 'li...","{'id': 2507, 'link': '/api/v1/venues/2507'}",ath,ath,...,Athletics,Sacramento,1901,"{'id': 103, 'name': 'American League', 'link':...","{'id': 200, 'name': 'American League West', 'l...","{'id': 1, 'link': '/api/v1/sports/1', 'name': ...",Athletics,Athletics,Athletics,True
1,"{'id': 115, 'name': 'Grapefruit League', 'link...",N,134,Pittsburgh Pirates,/api/v1/teams/134,2026,"{'id': 31, 'name': 'PNC Park', 'link': '/api/v...","{'id': 2526, 'link': '/api/v1/venues/2526'}",pit,pit,...,Pirates,Pittsburgh,1882,"{'id': 104, 'name': 'National League', 'link':...","{'id': 205, 'name': 'National League Central',...","{'id': 1, 'link': '/api/v1/sports/1', 'name': ...",Pittsburgh,Pittsburgh,Pirates,True
2,"{'id': 114, 'name': 'Cactus League', 'link': '...",N,135,San Diego Padres,/api/v1/teams/135,2026,"{'id': 2680, 'name': 'Petco Park', 'link': '/a...","{'id': 2530, 'link': '/api/v1/venues/2530'}",sdn,sd,...,Padres,San Diego,1968,"{'id': 104, 'name': 'National League', 'link':...","{'id': 203, 'name': 'National League West', 'l...","{'id': 1, 'link': '/api/v1/sports/1', 'name': ...",San Diego,San Diego,Padres,True
3,"{'id': 114, 'name': 'Cactus League', 'link': '...",N,136,Seattle Mariners,/api/v1/teams/136,2026,"{'id': 680, 'name': 'T-Mobile Park', 'link': '...","{'id': 2530, 'link': '/api/v1/venues/2530'}",sea,sea,...,Mariners,Seattle,1977,"{'id': 103, 'name': 'American League', 'link':...","{'id': 200, 'name': 'American League West', 'l...","{'id': 1, 'link': '/api/v1/sports/1', 'name': ...",Seattle,Seattle,Mariners,True
4,"{'id': 114, 'name': 'Cactus League', 'link': '...",N,137,San Francisco Giants,/api/v1/teams/137,2026,"{'id': 2395, 'name': 'Oracle Park', 'link': '/...","{'id': 2532, 'link': '/api/v1/venues/2532'}",sfn,sf,...,Giants,San Francisco,1883,"{'id': 104, 'name': 'National League', 'link':...","{'id': 203, 'name': 'National League West', 'l...","{'id': 1, 'link': '/api/v1/sports/1', 'name': ...",San Francisco,San Francisco,Giants,True

In [570]:
api_teams_df.shape

(30, 21)

In [571]:
api_teams_df.columns

Index(['springLeague', 'allStarStatus', 'id', 'name', 'link', 'season',
       'venue', 'springVenue', 'teamCode', 'fileCode', 'abbreviation',
       'teamName', 'locationName', 'firstYearOfPlay', 'league', 'division',
       'sport', 'shortName', 'franchiseName', 'clubName', 'active'],
      dtype='str')

In [572]:
api_teams_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   springLeague     30 non-null     object
 1   allStarStatus    30 non-null     str
 2   id               30 non-null     int64
 3   name             30 non-null     str
 4   link             30 non-null     str
 5   season           30 non-null     int64
 6   venue            30 non-null     object
 7   springVenue      30 non-null     object
 8   teamCode         30 non-null     str
 9   fileCode         30 non-null     str
 10  abbreviation     30 non-null     str
 11  teamName         30 non-null     str
 12  locationName     30 non-null     str
 13  firstYearOfPlay  30 non-null     str
 14  league           30 non-null     object
 15  division         30 non-null     object
 16  sport            30 non-null     object
 17  shortName        30 non-null     str
 18  franchiseName    30 non-null     str
 19  clubName         30 non-null     str
 20  active           30 non-null     bool
dtypes: bool(1), int64(2), object(6), str(12)
memory usage: 7.4+ KB

Add a column teams_info for just the name win percentages and division

In [573]:
teams_info = api_teams_df[["name", "season", "division"]]
teams_info

,name,season,division
0,Athletics,2026,"{'id': 200, 'name': 'American League West', 'l..."
1,Pittsburgh Pirates,2026,"{'id': 205, 'name': 'National League Central',..."
2,San Diego Padres,2026,"{'id': 203, 'name': 'National League West', 'l..."
3,Seattle Mariners,2026,"{'id': 200, 'name': 'American League West', 'l..."
4,San Francisco Giants,2026,"{'id': 203, 'name': 'National League West', 'l..."
5,St. Louis Cardinals,2026,"{'id': 205, 'name': 'National League Central',..."
6,Tampa Bay Rays,2026,"{'id': 201, 'name': 'American League East', 'l..."
7,Texas Rangers,2026,"{'id': 200, 'name': 'American League West', 'l..."
8,Toronto Blue Jays,2026,"{'id': 201, 'name': 'American League East', 'l..."
9,Minnesota Twins,2026,"{'id': 202, 'name': 'American League Central',..."
10,Philadelphia Phillies,2026,"{'id': 204, 'name': 'National League East', 'l..."
11,Atlanta Braves,2026,"{'id': 204, 'name': 'National League East', 'l..."
12,Chicago White Sox,2026,"{'id': 202, 'name': 'American League Central',..."
13,Miami Marlins,2026,"{'id': 204, 'name': 'National League East', 'l..."
14,New York Yankees,2026,"{'id': 201, 'name': 'American League East', 'l..."
15,Milwaukee Brewers,2026,"{'id': 205, 'name': 'National League Central',..."
16,Los Angeles Angels,2026,"{'id': 200, 'name': 'American League West', 'l..."
17,Arizona Diamondbacks,2026,"{'id': 203, 'name': 'National League West', 'l..."
18,Baltimore Orioles,2026,"{'id': 201, 'name': 'American League East', 'l..."
19,Boston Red Sox,2026,"{'id': 201, 'name': 'American League East', 'l..."
20,Chicago Cubs,2026,"{'id': 205, 'name': 'National League Central',..."
21,Cincinnati Reds,2026,"{'id': 205, 'name': 'National League Central',..."
22,Cleveland Guardians,2026,"{'id': 202, 'name': 'American League Central',..."
23,Colorado Rockies,2026,"{'id': 203, 'name': 'National League West', 'l..."
24,Detroit Tigers,2026,"{'id': 202, 'name': 'American League Central',..."
25,Houston Astros,2026,"{'id': 200, 'name': 'American League West', 'l..."
26,Kansas City Royals,2026,"{'id': 202, 'name': 'American League Central',..."
27,Los Angeles Dodgers,2026,"{'id': 203, 'name': 'National League West', 'l..."
28,Washington Nationals,2026,"{'id': 204, 'name': 'National League East', 'l..."
29,New York Mets,2026,"{'id': 204, 'name': 'National League East', 'l..."

In [574]:
teams_info.head(8)

,name,season,division
0,Athletics,2026,"{'id': 200, 'name': 'American League West', 'l..."
1,Pittsburgh Pirates,2026,"{'id': 205, 'name': 'National League Central',..."
2,San Diego Padres,2026,"{'id': 203, 'name': 'National League West', 'l..."
3,Seattle Mariners,2026,"{'id': 200, 'name': 'American League West', 'l..."
4,San Francisco Giants,2026,"{'id': 203, 'name': 'National League West', 'l..."
5,St. Louis Cardinals,2026,"{'id': 205, 'name': 'National League Central',..."
6,Tampa Bay Rays,2026,"{'id': 201, 'name': 'American League East', 'l..."
7,Texas Rangers,2026,"{'id': 200, 'name': 'American League West', 'l..."

In [575]:
teams_info["division"].iloc[0]

{'id': 200, 'name': 'American League West', 'link': '/api/v1/divisions/200'}

This shows how dirty and hard to read the dictionary inside of division is
A person really only needs to see the "name" portion of the dictionary

In [576]:
div = teams_info["division"]
div.iloc[0]

{'id': 200, 'name': 'American League West', 'link': '/api/v1/divisions/200'}

In [577]:
# div.iloc[0,29]['name']
division = teams_info["division"].apply(lambda x: x ["name"])
division

0        American League West
1     National League Central
2        National League West
3        American League West
4        National League West
5     National League Central
6        American League East
7        American League West
8        American League East
9     American League Central
10       National League East
11       National League East
12    American League Central
13       National League East
14       American League East
15    National League Central
16       American League West
17       National League West
18       American League East
19       American League East
20    National League Central
21    National League Central
22    American League Central
23       National League West
24    American League Central
25       American League West
26    American League Central
27       National League West
28       National League East
29       National League East
Name: division, dtype: str

In [578]:
teams_info["Division Str"] = division
teams_info.head(8)

,name,season,division,Division Str
0,Athletics,2026,"{'id': 200, 'name': 'American League West', 'l...",American League West
1,Pittsburgh Pirates,2026,"{'id': 205, 'name': 'National League Central',...",National League Central
2,San Diego Padres,2026,"{'id': 203, 'name': 'National League West', 'l...",National League West
3,Seattle Mariners,2026,"{'id': 200, 'name': 'American League West', 'l...",American League West
4,San Francisco Giants,2026,"{'id': 203, 'name': 'National League West', 'l...",National League West
5,St. Louis Cardinals,2026,"{'id': 205, 'name': 'National League Central',...",National League Central
6,Tampa Bay Rays,2026,"{'id': 201, 'name': 'American League East', 'l...",American League East
7,Texas Rangers,2026,"{'id': 200, 'name': 'American League West', 'l...",American League West

In [579]:
teams_info = teams_info[["name", "season", "Division Str"]]
teams_info

                     name  season             Division Str
0               Athletics    2026     American League West
1      Pittsburgh Pirates    2026  National League Central
2        San Diego Padres    2026     National League West
3        Seattle Mariners    2026     American League West
4    San Francisco Giants    2026     National League West
5     St. Louis Cardinals    2026  National League Central
6          Tampa Bay Rays    2026     American League East
7           Texas Rangers    2026     American League West
8       Toronto Blue Jays    2026     American League East
9         Minnesota Twins    2026  American League Central
10  Philadelphia Phillies    2026     National League East
11         Atlanta Braves    2026     National League East
12      Chicago White Sox    2026  American League Central
13          Miami Marlins    2026     National League East
14       New York Yankees    2026     American League East
15      Milwaukee Brewers    2026  National League Central
16     Los Angeles Angels    2026     American League West
17   Arizona Diamondbacks    2026     National League West
18      Baltimore Orioles    2026     American League East
19         Boston Red Sox    2026     American League East
20           Chicago Cubs    2026  National League Central
21        Cincinnati Reds    2026  National League Central
22    Cleveland Guardians    2026  American League Central
23       Colorado Rockies    2026     National League West
24         Detroit Tigers    2026  American League Central
25         Houston Astros    2026     American League West
26     Kansas City Royals    2026  American League Central
27    Los Angeles Dodgers    2026     National League West
28   Washington Nationals    2026     National League East
29          New York Mets    2026     National League East

In [580]:
connection = sqlite3.connect("../data/mlb.db")

In [581]:
team_records.to_sql(
    "team_records",
    connection,
    if_exists="replace",
    index=False
)

30

In [582]:
query = """
SELECT *
FROM team_records;
"""

pd.read_sql_query(query, connection)

                       Tm   W    L   W-L%    GB  Win_Percentage
0       Toronto Blue Jays  94   68  0.580    --        0.580247
1        New York Yankees  94   68  0.580    --        0.580247
2          Boston Red Sox  89   73  0.549   5.0        0.549383
3          Tampa Bay Rays  77   85  0.475  17.0        0.475309
4       Baltimore Orioles  75   87  0.463  19.0        0.462963
5     Cleveland Guardians  88   74  0.543    --        0.543210
6          Detroit Tigers  87   75  0.537   1.0        0.537037
7      Kansas City Royals  82   80  0.506   6.0        0.506173
8         Minnesota Twins  70   92  0.432  18.0        0.432099
9       Chicago White Sox  60  102  0.370  28.0        0.370370
10       Seattle Mariners  90   72  0.556    --        0.555556
11         Houston Astros  87   75  0.537   3.0        0.537037
12          Texas Rangers  81   81  0.500   9.0        0.500000
13              Athletics  76   86  0.469  14.0        0.469136
14     Los Angeles Angels  72   90  0.444  18.0        0.444444
15  Philadelphia Phillies  96   66  0.593    --        0.592593
16          New York Mets  83   79  0.512  13.0        0.512346
17          Miami Marlins  79   83  0.488  17.0        0.487654
18         Atlanta Braves  76   86  0.469  20.0        0.469136
19   Washington Nationals  66   96  0.407  30.0        0.407407
20      Milwaukee Brewers  97   65  0.599    --        0.598765
21           Chicago Cubs  92   70  0.568   5.0        0.567901
22        Cincinnati Reds  83   79  0.512  14.0        0.512346
23    St. Louis Cardinals  78   84  0.481  19.0        0.481481
24     Pittsburgh Pirates  71   91  0.438  26.0        0.438272
25    Los Angeles Dodgers  93   69  0.574    --        0.574074
26       San Diego Padres  90   72  0.556   3.0        0.555556
27   San Francisco Giants  81   81  0.500  12.0        0.500000
28   Arizona Diamondbacks  80   82  0.494  13.0        0.493827
29       Colorado Rockies  43  119  0.265  50.0        0.265432

In [ ]:
# add rate_team from src/main

In [ ]:
print(rate_team(0.610))
print(rate_team(0.570))
print(rate_team(0.520))
print(rate_team(0.420))